In [ ]:
import pandas as pd

카페 데이터가 검색 결과와 일치하지 않음 😢 -> 새로 생성

In [ ]:
df = pd.read_csv('/content/drive/Shareddrives/2021 CCP/천신만고 끝에 얻은 데이터/KT 데이터 재구성/place_cut/201905/201905KT_Jegi.csv')
df = df.drop(['Unnamed: 0'], axis=1)

cafe_df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2021CCP/kt_data/data_folder/jegi_cafe.xlsx')

In [ ]:
# 모든 셀
id_list = df['id'].unique()
x_list = df['x'].unique()
y_list = df['y'].unique()

In [ ]:
cells = pd.DataFrame(columns=['id','x','y'])
cells['id'] = id_list
cells['x'] = x_list
cells['y'] = y_list

In [ ]:
!pip install geopandas
import geopandas as gpd
from shapely.geometry import Polygon

In [ ]:
# 경도 1도 = 88.8km (위도 37도 기준)
# 위도 1도 = 111km
# 경도 → 25/88800, 위도 → 25/111000

x_ = 25/88800
y_ = 25/111000

rec_cells = cells.copy()
rec_cells['geometry'] = rec_cells.apply(lambda row : Polygon([(row['y']+y_,row['x']+x_),(row['y']+y_,row['x']-x_),(row['y']-y_,row['x']-x_),(row['y']-y_,row['x']+x_)]), axis=1)
rec_cells = gpd.GeoDataFrame(rec_cells, geometry='geometry')

k = [list(rec_cells.geometry.exterior[row_id].coords) for row_id in range(rec_cells.shape[0])]

In [ ]:
import folium

m = folium.Map(location=[37.583772, 127.037004], zoom_start=15)

for i in range(len(rec_cells)):
  folium.Polygon(locations = k[i],fill = True,tooltip = rec_cells['id'][i]).add_to(m)
  folium.CircleMarker([rec_cells['y'][i],rec_cells['x'][i]],color='red',radius = 1, tooltip=rec_cells['id'][i]).add_to(m)

for i in range(len(cafe_df)):
  folium.Marker([cafe_df['y'][i],cafe_df['x'][i]],tooltip=cafe_df['name'][i]).add_to(m)

m

In [ ]:
from shapely.geometry import Point

In [ ]:
cafe_df['geometry'] = cafe_df.apply(lambda row : Point([row['y'], row['x']]), axis=1)
cafe_df = gpd.GeoDataFrame(cafe_df, geometry='geometry')

In [ ]:
rec_cells['have_cafe'] = False
for i in range(len(rec_cells)):
  for j in range(len(cafe_df)):
    if rec_cells.geometry[i].contains(cafe_df.geometry[j]):
      rec_cells['have_cafe'][i] = True

In [ ]:
res_cells = rec_cells.copy()
res_cells = res_cells[res_cells['have_cafe']==True]
res_cells = res_cells.drop(['have_cafe','geometry'], axis=1)
res_cells = res_cells.reset_index(drop=True)

In [ ]:
res_cells

id           x          y
0   51825348  127.032555  37.586058
1   51837520  127.033220  37.578405
2   51837537  127.033121  37.586063
3   51849710  127.033781  37.578860
4   51861910  127.034283  37.583820
5   51861914  127.034259  37.585621
6   51861915  127.034254  37.586072
7   51861918  127.034236  37.587423
8   51874108  127.034796  37.587878
9   51886298  127.035357  37.588333
10  51898465  127.036050  37.578428
11  51898473  127.036004  37.582031
12  51898486  127.035929  37.587888
13  51898488  127.035917  37.588789
14  51898489  127.035911  37.589239
15  51910655  127.036611  37.578883
16  51935056  127.037609  37.589253
17  51959411  127.038875  37.578901
18  51959430  127.038765  37.587460
19  52032548  127.042253  37.580280

In [ ]:
import numpy as np

In [ ]:
cell_id = df['id'].unique()
# 글씨에 가려져서 삭제한 셀 : 51947242 51947241 51935052 51935053 51922863 51910674
remove_id = [51947241, 51947242, 51935052, 51935053, 51922863, 51910674]
cell_id = np.setdiff1d(cell_id, remove_id)
cell_id.sort()

In [ ]:
from PIL import Image
import numpy as np
ans = [[              7,8,9,10                                                      ],
       [              7,8,9,10,11                                                   ],
       [              7,8,9,10,11,12                                                ],
       [              7,8,9,10,11,12,13,14                                          ],
       [        4,5,6,7,8,9,10,11,12,13,14,15                                       ],
       [    2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17                                 ],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18                              ],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19                           ],
       [      3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20                        ],
       [0,1,2,3,4,      8,9,10,11,12,13,14,15,16,17,18,19,20,21                     ],
       [0,1,2,3,4,5,6,7,8,9,10,         14,15,16,17,18,19,20,21,22                  ],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,   17,18,19,20,21,22,23,24            ],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,         21,22,23,24,25,26,27,28],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,      22,23,24,25,26,27,28],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,      22,   24,25,26,27,28],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,      22,23,24,      27,28],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27   ],
       [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],
       [  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,   28],
       [  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,   20,            25,26,   28],
       [  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18                              ],
       [    2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18                              ],
       [    2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18                              ],
       [      3,4,5,6,7,8,9,10,11,12,13,14,15                                       ],
       [      3,      7,8,9,10,11                                                   ],
       [              7                                                             ]]

def crop_image(hor, ver, left, up, right, down, ori_image):
  if ver in ans[hor]:
    image_list.append(np.array(ori_image.crop((left,up,right,down))))

In [ ]:
image_list = []

In [ ]:
ori_image = Image.open('/content/drive/MyDrive/Colab Notebooks/2021CCP/kt_data/SG05/jegi.png')
length = 26.6
left = 628
up = 821
for hor in range(26):
  for ver in range(29):
    x0, x1, y0, y1 = (hor+0)*length, (hor+1)*length, (ver+0)*length, (ver+1)*length
    crop_image(hor, ver, left+x0, up-y1, left+x1, up-y0, ori_image)

In [ ]:
Image.fromarray(image_list[0])

In [ ]:
cell_id[0]

51764393

In [ ]:
# 이미지의 색 면적 분석 후, res_cells의 셀들에 한해서, id를 cell_id에서 찾아 인덱스를 구하고,
# 이를 활용해 percent_res에서 해당 이미지를 찾고, 도출한 회귀계수 및 상수를 활용하여 적절한 인구수를 배분

In [ ]:
bgr_list = [[[194,230,254],[111,193,233]],
            [[184,131,237],[164,176,223]],
            [[138,113,246]],
            [[0,122,255]],
            [[78,4,252],[42,65,247]],
            [[0,0,190],[18,117,246],[27,88,199]],
            [[255,167,62],[255,109,93]],
            [[44,106,51],[64,79,10],[51,102,51]],
            [[148,213,161],[51,126,96]],
            [[172,181,123],[255,242,159]]]

In [ ]:
import cv2

percent_res = np.zeros([len(image_list),10])

for k in range(len(image_list)):

  # PIL to OpenCV
  cutted = Image.fromarray(image_list[k])
  cutted = np.array(cutted)
  cutted = cv2.cvtColor(cutted, cv2.COLOR_BGR2RGB)
  #cutted = cutted.reshape((cutted.shape[0] * cutted.shape[1], 3))

  # BGR로 특정 색을 추출하는 함수
  def bgrExtraction(image, bgrLower, bgrUpper):
    img_mask = cv2.inRange(image, bgrLower, bgrUpper)
    result = cv2.bitwise_and(image, image, mask=img_mask)
    return result

  for i in range(10):
    for j in range(len(bgr_list[i])):

      # BGR로 색추출
      bgrLower = np.array(bgr_list[i][j]) # 추출할 색의 하한
      bgrUpper = np.array(bgr_list[i][j]) # 추출할 색의 상한
      bgrResult = bgrExtraction(cutted, bgrLower, bgrUpper)

      # 면적(개수) 계산
      temp1 = np.count_nonzero(bgrResult, axis=-1)
      temp2 = np.where(temp1>0,1,0)
      percent_res[k][i] += temp2.sum()

In [ ]:
# normalized ver
percent_res_n = percent_res.copy()
#percent_res_n = (percent_res_copy.transpose() / percent_res_n.sum(axis=1)).transpose() * 27 * 27 
percent_res_n = percent_res_n / (27 * 27)

In [ ]:
#for i in range(len(res_cells)):
#  percent_res[np.where(cell_id == res_cells['id'][i])[0][0]]

k = np.where(cell_id == res_cells['id'][13])[0][0]
print(percent_res[k])
print(percent_res_n[k])
print(cell_id[k])
Image.fromarray(image_list[k])

[ 0. 59.  0.  0. 22.  1.  0.  0.  0.  0.]
[0.         0.08093278 0.         0.         0.03017833 0.00137174
 0.         0.         0.         0.        ]
51898488


In [ ]:
df_copy = df.copy()
df_copy = df_copy[['etl_ymd','id','x','y','timezn_cd','total']]
df_copy[df_copy['id'] == cell_id[k]][13:14]

etl_ymd        id           x          y  timezn_cd  total
6978  20190501  51898488  127.035917  37.588789         16  54.01

In [ ]:
var = 54.01  # 위에서의 total 값 (= input)

In [ ]:
# 최종 결과
# 주거 상업 휴양 학교 교통 공공 하천 산림 초지 나지
#  +    -    +    -    -    -    -    0    -    -

co = np.array([9.33634641e+00,-1.29029199e+01,1.46881054e+01,-7.78535967e+00,-8.59396583e-01,-2.05496450e+00,-4.44089210e-16,0.00000000e+00,-8.05613916e+00,-4.10763925e+01])
ans = (var - 28.12855268461152) * co
ans = ans * percent_res_n[k]
ans

array([  0.        , -27.02719925,   0.        ,  -0.        ,
        -0.67123924,  -0.07295673,  -0.        ,   0.        ,
        -0.        ,  -0.        ])

In [ ]:
# 처리 과정 보완

co2 = np.array([9.33634641e+00,-1.29029199e+01,1.46881054e+01,-7.78535967e+00,-8.59396583e-01,-2.05496450e+00,-4.44089210e-16,0.00000000e+00,-8.05613916e+00,-4.10763925e+01])
co2 = co2 / abs(co2.sum())
ans2 = - (var + 28.12855268461152) * co2
ans2 = ans2 * percent_res_n[k]
ans2

array([-0.        ,  1.76090115, -0.        ,  0.        ,  0.0437332 ,
        0.00475334,  0.        , -0.        ,  0.        ,  0.        ])

In [ ]:
# 처리 과정 보완 2

co3 = np.array([9.33634641e+00,-1.29029199e+01,1.46881054e+01,-7.78535967e+00,-8.59396583e-01,-2.05496450e+00,-4.44089210e-16,0.00000000e+00,-8.05613916e+00,-4.10763925e+01])
ans3 = abs(var - 28.12855268461152) * co3 * co3
ans3 = ans3 * percent_res_n[k]
ans3 /= abs(ans3.sum()) / var
ans3

array([0.00000000e+00, 5.38976724e+01, 0.00000000e+00, 0.00000000e+00,
       8.91562765e-02, 2.31713130e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00])

In [ ]:
# 처리 과정 보완 3

co4 = np.array([9.33634641e+00,-1.29029199e+01,1.46881054e+01,-7.78535967e+00,-8.59396583e-01,-2.05496450e+00,-4.44089210e-16,0.00000000e+00,-8.05613916e+00,-4.10763925e+01])
co4 += abs(co4.min())
co4 /= co4.sum()
ans4 = var * co4
#ans4 = abs(var - 28.12855268461152) * co4  # 28 무시했을 때와 오차 거의 X
ans4 = ans4 * percent_res_n[k]
ans4 /= abs(ans4.sum()) / var
ans4

array([ 0.        , 34.71626329,  0.        ,  0.        , 18.47876273,
        0.81497397,  0.        ,  0.        ,  0.        ,  0.        ])

In [ ]:
# 처리 과정 보완 4 - 오류

co5 = np.array([9.33634641e+00,-1.29029199e+01,1.46881054e+01,-7.78535967e+00,-8.59396583e-01,-2.05496450e+00,-4.44089210e-16,0.00000000e+00,-8.05613916e+00,-4.10763925e+01])
ans5 = var * co5
ans5 = ans5 * percent_res_n[k]
ans5 += abs(ans5.min())
ans5 /= abs(ans5.sum()) / var
ans5

array([6.01952757, 0.        , 6.01952757, 6.01952757, 5.87002843,
       6.00327857, 6.01952757, 6.01952757, 6.01952757, 6.01952757])

In [ ]:
# 결론

import math

for i in range(10):
  ans4[i] = math.floor(ans4[i])

ans4  # 주거 상업 휴양 학교 교통 공공 하천 산림 초지 나지

array([ 0., 34.,  0.,  0., 18.,  0.,  0.,  0.,  0.,  0.])